### ISSUE TITLE
Certain building maps don't render

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/sitenow_maps#22]
https://maps.uiowa.edu/riv8

**Comment by joewhitsitt** [comment]
Children's Hospital too. Renaming issue.
https://maps.uiowa.edu/sfch

**Comment by markahrens** [comment]
This is an issue with the data coming from facilities. If the abbreviation from the SIMS database doesn't line up with a group of building data points in Arc, then the map doesn't render.

**Comment by joewhitsitt** [comment]
This is ongoing with certain buildings and relies on the implementation of several data layers that are maintained by facilities. The two buildings in this issue have been fixed. Working with facilities to sync these up better.
